### ISSUE TITLE
Push to NPM 

### ISSUE THREAD

**Issue by virgilvox** [GeenenTijd/llrp-nodejs#1]
Hi! Thanks for making this it made some work easy. However could you push this to NPM under the name llrp or something? When I try to include this as a dependancy in package.json I get issues.

**Comment by GlennGeenen** [comment]
I published it as llrp.

This was just a test to work with lrrp in nodejs, it has some serious issues. I haven't had the time to do a real attempt to port lrrp toolkit to nodejs. That was ultimately the goal, I hope I'll find time for that soon.
