### ISSUE TITLE
Connection timeout

### ISSUE THREAD

**Issue by NetOpWibby** [GeenenTijd/llrp-nodejs#3]
First, thank you for this module. I'd rather work with JavaScript than Java, especially for hardware. Gotta love abstractions.

I've got this module working but after I see `Sending ENABLE_EVENTS_AND_REPORTS` in Terminal, the connection times out. I'm not sure if that's expected behavior to be quite honest. However, I don't see tag reads either. I have the xArray R680, if that helps.

**Comment by GlennGeenen** [comment]
This module is a test module, I just made it so it worked for the readers I used. It needs to implement the entire LLRP protocol to be of any use. I once started on this but I do not have the time/patience to properly implement it in JavaScript. I you need it for serious software purposes use something like [LLRP toolkit](http://www.llrp.org) or libraries provided by the reader manufacturer.

**Comment by NetOpWibby** [comment]
Ah well, that makes sense. Would you be able to point me in the right direction in terms of figuring out how to get started with implementing the rest of the protocol (or at least the parts I want)?

**Comment by GlennGeenen** [comment]
[LLRP protocol](http://www.gs1.org/epcrfid/epc-rfid-llrp/1-1-0)

I guess it's easier to port a Java version. Making bindings to an existing C++ library might be the least work. I didn't continue since it's a lot of work for very little gain.

**Comment by NetOpWibby** [comment]
I understand. Thanks for your help!
